### ISSUE TITLE
标签页最上级变为某个串( ﾟ∀。)

### ISSUE THREAD

**Issue by qiyi71w** [orzogc/xdnmb#11]
平台：IOS
今天不小心在一个串里面点了“新标签页打开”，现在我的霞岛左上角返回的最上级变成了那个串，该咋恢复默认啊( ﾟ∀。)
版块页面好像不能新建标签页，如果我去另外一个串新建标签页然后点叉的话，最上级又跑到另外一个串了･ﾟ( ﾉд`ﾟ)

**Comment by orzogc** [comment]
不能在标签页列表（点击底边栏左起第三个按钮打开）里切换标签吗？
