### ISSUE TITLE
[bug]左边菜单只有一个板块

### ISSUE THREAD

**Issue by xiaochopin** [orzogc/xdnmb#5]
![Screenshot_2022-10-29-13-26-34-272_org xnonymous xdnmb](https://user-images.githubusercontent.com/102412959/198815507-89b018f7-aa1c-414f-ba50-bcaa6b53301d.jpg)

**Comment by orzogc** [comment]
这不是板块，而是标签页，版块需要从右往左划

**Comment by xiaochopin** [comment]
串内新标签页原来是这样子用的吗(;´Д`)
