### ISSUE TITLE
似乎有串内容重复出现的问题

### ISSUE THREAD

**Issue by jerrywcy** [orzogc/xdnmb#6]
大概就是有一段后面的内容被复制了一遍插到了前面的效果，如图
![Screenshot_2022-10-30-16-11-34-62_cb450d306f2098915790b36613d6a1d5](https://user-images.githubusercontent.com/34678939/198869031-a051343d-3ea1-45c5-850f-ae455f6aa5b6.jpg)

**Comment by jerrywcy** [comment]
哎呀放错图了
![Uploading Screenshot_2022-10-30-16-11-51-75.jpg…]()

**Comment by jerrywcy** [comment]
哎呀放错图了( ﾟ∀。)
![Screenshot_2022-10-30-16-11-51-75](https://user-images.githubusercontent.com/34678939/198869104-9aab5fb4-9272-4d5f-884f-f5b112c81cfa.jpg)

**Comment by orzogc** [comment]
中间多插了下一页进去，请问是怎么操作造成的？能否复现？

**Comment by jerrywcy** [comment]
> 中间多插了下一页进去，请问是怎么操作造成的？能否复现？

我仔细回忆了一下，大概是这样的：

当时网比较烂，我向下拉了之后好久都没有加载出来，我就又点了一遍那个红色的connection reset的提示，然后加载出来就这样子了

刚才又出现了一次( ﾟ∀。)

![Screenshot_2022-10-30-17-09-34-73](https://user-images.githubusercontent.com/34678939/198871050-dc95f289-c9d3-480f-905a-f822333991cf.jpg)

**Comment by jerrywcy** [comment]
完了，刚没有第二步也出现这个问题了( ﾟ∀。)

**Comment by jerrywcy** [comment]
![Screenshot_2022-10-30-17-58-16-06](https://user-images.githubusercontent.com/34678939/198872864-fe906edb-b64c-490b-88e1-b173360a62d2.jpg)

**Comment by orzogc** [comment]
应该修复了，感谢您的反馈

**Comment by jerrywcy** [comment]
好耶\( ﾟ∀。)/

**Comment by jerrywcy** [comment]
真是好快的速度啊（感叹
