### ISSUE TITLE
关于退出草稿的二次确认框的按钮逻辑问题

### ISSUE THREAD

**Issue by YukiChiyoda** [orzogc/xdnmb#8]
![Screenshot_2023-01-23-19-32-26-781_org.xnonymous.xdnmb.jpg](https://user-images.githubusercontent.com/68385758/214030748-df6d2c16-84f3-4873-b183-f58918a502e7.jpg)

"保存"与"不保存"(即现有的"关闭")应属同一逻辑，"取消"应属与是否保存不同的另一逻辑，因此是否有必要将"取消"放在左侧而将"保存"与"关闭"放在右侧呢( ›´ω`‹ )

**Comment by YukiChiyoda** [comment]
定位到`/lib/app/modules/post_list.dart`中的
**792-794行**
```
          TextButton( 
               onPressed: () => Get.back<bool>(result: true), 
               child: const Text('关闭')), 
```
与**799-802行**
```
               if (canPost) 
                 TextButton( 
                     onPressed: () => Get.back<bool>(result: false), 
                     child: const Text('取消')),
```
肥哥辛苦了~

**Comment by orzogc** [comment]
这个顺序应该不会改了，文字改一下吧
